import Head from "next/head"
import Image from "next/image"
import Link from "next/link"
import MainLayout from "../../components/layout/MainLayout"


import styles from "../../styles/host/Home.module.css"
import HomePageStyles from "../../styles/Home.module.css"

import Section08Img01 from "../../assets/img/home-page/section-08-img-01.png"
import Section08Img02 from "../../assets/img/home-page/section-08-img-02.png"
import Section08Img03 from "../../assets/img/home-page/section-08-img-03.png"

import HeroSectiomImg from "../../assets/img/Renter/HeroSection.png"
import Section02Img01 from "../../assets/img/Renter/Section02Img01.png"
import Section02Img02 from "../../assets/img/Renter/Section02Img02.png"

import Section03Img01 from "../../assets/img/Renter/Section03Img01.png"
import AppStore from "../../assets/img/Renter/AppStore.png"
import GooglePlay from "../../assets/img/Renter/GooglePlay.png"


import { Navigation, Autoplay, Pagination } from 'swiper';
import { Swiper, SwiperSlide } from "swiper/react"
import 'swiper/css';
import 'swiper/css/navigation';
import 'swiper/css/pagination';



const index = () => {

    const pagination = {
        clickable: true,
        renderBullet: function (index, className) {
            return '<span class="' + className + '">' + (index + 1) + "</span>";
        },
    };

    return (
        <>
            <Head>
                <title>VEHDE - Renter</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <MainLayout>
                <section id={styles.heroSection} className='heroSection' style={{ background: "#DE4F4D" }}>
                    <div className="py-5">
                        <div className='container'>
                            <div className='row row-cols-lg-2'>
                                <div>
                                    <h1 style={{ color: "white" }}>Renter</h1>
                                    <h4 style={{ color: "white" }}>Stay ahead!</h4>
                                    <p style={{ color: "white" }}>Whether it is for daily business activities, holiday leisure, or weekend trips, VEHDE is committed to improving people’s accessibility to a variety of cars in way more convenient arrangements.
                                        <br />
                                        <br />
                                        Flexibility and innovation are critical to our business strategies at VEHDE.</p>
                                    <h4 style={{ color: "white" }}>The perfect car for your trip is
                                        just around the corner.</h4>
                                    <Link href={`/Renter/BrowseCars`} className='my-btn' id="signup" style={{ width: "fit-content", background: "#FFFFFF", color: "#DE4F4D" }}>Browse available cars</Link>
                                </div>
                                <div>
                                    <Image src={HeroSectiomImg} alt="Hero Section Img" className="w-100 h-auto" />
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
                <section id={HomePageStyles.section03} className='mb-5 mt-5'>
                    <div className="container">
                        <div className="row row-cols-md-2 row-cols-1 align-items-center">
                            <div className="col">
                                <h2>Travel with a personal driver</h2>
                                <p>Whether it is for business or for private, in budget or first class style. With VEHDE ride, you get ride services tailored to your needs. By logging in to our platform, you benefit from a choice of different booking classes and the largest coverage of ride services worldwide. Download the VEHDE app now!</p>
                                <div className='d-flex align-items-center gap-2 d-none'>
                                    <a href="#">See how our collaborative strategy works</a>
                                    {/* <span><Image src={Section03ArrowIcon} alt="Arrow Icon" /></span> */}
                                </div>
                            </div>
                            <div className="col d-flex flex-lg-row flex-column">
                                <div className={`flex-1 ${HomePageStyles.section03FirstCol}`}>
                                    <Image src={Section02Img01} alt="" className='img-fuild' />
                                </div>
                                <div className='flex-1'>
                                    <Image src={Section02Img02} alt="" className='img-fluid' />
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
                <section id={HomePageStyles.section07} className={styles.sliderSection}>
                    <div className="container">
                        <h2 className="text-center">Find your drive in 3 easy steps</h2>
                        <div className="wrapper">
                            <Swiper
                                spaceBetween={30}
                                centeredSlides={false}
                                autoplay={{
                                    delay: 10500,
                                    disableOnInteraction: true,
                                }}
                                navigation={true}
                                pagination={pagination}
                                modules={[Autoplay, Navigation, Pagination]}
                                slidesPerView={1}
                            >
                                <SwiperSlide>
                                    <div className="row row-cols-md-2 row-cols-1 align-items-center">
                                        <Image src={Section03Img01} alt="Air Bnb" className='img-fluid w-100 mx-auto' style={{ maxWidth: "350px" }} />
                                        <div className="text-start">
                                            <h4 className={styles.sliderHeading}>Get the VEHDE app</h4>
                                            <p className={styles.sliderSubHeading}>Download and join for free. You'll never pay a membership fee.</p>
                                            <div className="row row-cols-2">
                                                <Image src={AppStore} alt="" className="w-auto" />
                                                <Image src={GooglePlay} alt="" className="w-auto" />
                                            </div>
                                        </div>
                                    </div>
                                </SwiperSlide>
                                <SwiperSlide>
                                    <div className="row row-cols-md-2 row-cols-1 align-items-center">
                                        <Image src={Section03Img01} alt="Air Bnb" className='img-fluid w-100 mx-auto' style={{ maxWidth: "350px" }} />
                                        <div className="text-start">
                                            <h4 className={styles.sliderHeading}>Get the VEHDE app</h4>
                                            <p className={styles.sliderSubHeading}>Download and join for free. You'll never pay a membership fee.</p>
                                            <div className="row row-cols-2">
                                                <Image src={AppStore} alt="" className="w-auto" />
                                                <Image src={GooglePlay} alt="" className="w-auto" />
                                            </div>
                                        </div>
                                    </div>
                                </SwiperSlide>
                                <SwiperSlide>
                                    <div className="row row-cols-md-2 row-cols-1 align-items-center">
                                        <Image src={Section03Img01} alt="Air Bnb" className='img-fluid w-100 mx-auto' style={{ maxWidth: "350px" }} />
                                        <div className="text-start">
                                            <h4 className={styles.sliderHeading}>Get the VEHDE app</h4>
                                            <p className={styles.sliderSubHeading}>Download and join for free. You'll never pay a membership fee.</p>
                                            <div className="row row-cols-2">
                                                <Image src={AppStore} alt="" className="w-auto" />
                                                <Image src={GooglePlay} alt="" className="w-auto" />
                                            </div>
                                        </div>
                                    </div>
                                </SwiperSlide>
                            </Swiper>
                        </div>
                    </div>
                </section>
                <section id={styles.section08}>
                    <div className="container">
                        <div className="wrapper">
                            <h2 className='text-center'>Mask and Safety</h2>
                            <div className="row row-cols-lg-3 row-cols-1 align-items-center">
                                <div className="col p-3">
                                    <div className="text-center d-flex flex-column align-items-center justify-content-between">
                                        <Image src={Section08Img01} alt="Car in hand" />
                                        <h3>Your safety, our no 1 priority.</h3>
                                        <p>We are fully committed to your safety, even as our innovative strategies help enhance your accessibility to mobility of greater value to your productivity.</p>
                                    </div>
                                </div>
                                <div className="col p-3">
                                    <div className="text-center d-flex flex-column align-items-center justify-content-between">
                                        <Image src={Section08Img02} alt="Car in hand" />
                                        <h3>Mask & Social Safety</h3>
                                        <p>With your support, when you observe safety procedures, every day, we protect our great asset –Health.</p>
                                        <Link href="MaskSocialSafety" className='d-block' style={{ paddingBottom: "15px" }}>Learn more about mask and social safety</Link>
                                    </div>
                                </div>
                                <div className="col p-3">
                                    <div className="text-center d-flex flex-column align-items-center justify-content-between">
                                        <Image src={Section08Img03} alt="Car in hand" />
                                        <h3>COVID-19 Vaccine</h3>
                                        <p>Let’s crunch the virus! Our commitment to vaccination moves us closer to full recovery in our various communities.</p>
                                        <Link href="VaccinationProgram">Learn more about vaccination program</Link>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
            </MainLayout>
        </>
    )
}

export default index