import Head from 'next/head'
import React from 'react'
import MainLayout from '../components/layout/MainLayout'
import styles from "../styles/Login.module.css"
import Link from 'next/link'

const Authorization = () => {

    const handleSubmit = (e) => {
        e.preventDefault()
        alert("Form Submited")
    }

    return (
        <>
            <Head>
                <title>VEHDE - Authorization</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <MainLayout>
                <section id={styles.mainSection}>
                    <div className="bg">
                        <div className="container">
                            <div className="formWrapper">
                                <h2 className="text-center">VEHDE</h2>
                                <p>An authorization code was sent to your mobile phone number</p>
                                <h3>XXX-XXX-1984 </h3>
                                <div className="inputWrapper">
                                    <form action="" onSubmit={handleSubmit} className="mt-5 mb-4">
                                        <div className="inputBox">
                                            <label htmlFor="">Please enter the authorization code below</label>
                                            <input type="text" placeholder='Enter your code' />
                                        </div>
                                        <button className='my-btn' type='button'>Next</button>
                                    </form>
                                    <div className="mt-3 text-center">
                                        <p>Text code to (***)-***-1984</p>
                                    </div>
                                    <div className="d-flex justify-content-center align-items-center">
                                        <button className='outline-none bg-white border-0'>Request another authorization code</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
            </MainLayout>
        </>
    )
}

export default Authorization