import Head from "next/head";
import React from "react";
import MainLayout from "../components/layout/MainLayout";
import styles from "../styles/Login.module.css";
import Link from "next/link";
import { useRouter } from "next/router";

const Login = () => {
  const router = useRouter();

  const handleSubmit = (e) => {
    e.preventDefault();

    const form = e.target;

    const emailOrPhone = form.emailOrPhone.value;

    emailOrPhone === ""
      ? alert("Please enter your email or phone number")
      : fetch("http://localhost:5000/host/login", {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
          },
          body: JSON.stringify({ emailOrPhone }),
        })
          .then((res) => res.json())
          .then((data) => {
            console.log(data);
            localStorage.setItem("user", JSON.stringify(data));
            if (data.email === emailOrPhone || data.phone === emailOrPhone) {
              router.push("/dashboard/profile");
            }
            else {
              alert("User not found");
            }
          })
          .catch((err) => console.log(err));

    // router.push("/WelcomeOnboard")
  };

  return (
    <>
      <Head>
        <title>VEHDE - Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout>
        <section id={styles.mainSection}>
          <div className="bg">
            <div className="container">
              <div className="formWrapper">
                <h2 className="text-center">VEHDE</h2>
                <div className="inputWrapper">
                  <form action="" onSubmit={handleSubmit} className="mt-5 mb-4">
                    <div className="inputBox">
                      <label htmlFor="">Sign in</label>
                      <input
                        type="text"
                        name="emailOrPhone"
                        placeholder="Email, Phone Number or VEHDE ID"
                      />
                    </div>
                    <button className="my-btn" type="submit">
                      Login
                    </button>
                  </form>
                  <div className="d-flex justify-content-center align-items-center">
                    <Link href="/SigninUpWithVehde">
                      New to VEHDE? <span>Sign up</span>
                    </Link>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
      </MainLayout>
    </>
  );
};

export default Login;
