import Head from 'next/head'
import React from 'react'
import MainLayout from '../components/layout/MainLayout'
import styles from "../styles/SigninUpWithVehde.module.css"

import Section02Img01 from "../assets/img/signin-up-with-vehde/section-02-img-01.png"
import Section02Img02 from "../assets/img/signin-up-with-vehde/section-02-img-02.png"
import Image from 'next/image'
import Link from 'next/link'

const SigninUpWithVehde = () => {
    return (
        <>
            <Head>
                <title>VEHDE - Signin Up With Vehde</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <MainLayout>
                <section id={styles.heroSection} className="heroSection">
                    <div className="container">
                        <div className="wrapper">
                            <div className="row align-items-center">
                                <div className="col-lg-5 mb-lg-0 mb-5">
                                    <h1>Signing up with VEHDE</h1>
                                    <p>Thank you for your interest in VEHDE. Please review your options below.</p>
                                </div>
                                <div className="col-lg-7 text-center">
                                    {/* <Image src={HeroSectionImg} alt="Patent Vaccination Program Image" className='img-fluid' /> */}
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
                <section id={styles.section02}>
                    <div className="container">
                        <div className="wrapper">
                            <div className="row row-cols-lg-2 row-cols-1 mt-5 align-items-center">
                                <div className="col text-lg-start text-center">
                                    <Image src={Section02Img01} className='img-fluid' />
                                </div>
                                <div className="col">
                                    <div className="mb-4">
                                        <h3>Host</h3>
                                        <p>Whether you are an individual or a car rental company, you can become a host by listing your car to rent. <span>Stay ahead! List your car today.</span></p>
                                        <div className="d-flex mt-4">
                                            <Link href="#" className='my-btn'>Apply to host</Link>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div className="row row-cols-lg-2 row-cols-1 align-items-center mt-5">
                                <div className="col order-lg-1 order-2">
                                    <div>
                                        <h3>Renter</h3>
                                        <p>Whether it is for daily business activities, holiday leisure, or weekend trips, VEHDE is committed to improving people’s accessibility to a variety of cars in way more convenient arrangements.</p>
                                        <div className="d-flex mt-4">
                                            <Link href="#" className='my-btn'>&nbsp;&nbsp; Rent a car &nbsp;&nbsp;</Link>
                                        </div>
                                    </div>
                                </div>
                                <div className="col text-lg-end text-center order-lg-2 order-1">
                                    <Image src={Section02Img02} className='img-fluid' />
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
            </MainLayout>
        </>
    )
}

export default SigninUpWithVehde