import Head from 'next/head'
import styles from '../styles/SmartGuide.module.css'
import MainLayout from "../components/layout/MainLayout"
import Image from 'next/image'
import Link from "next/link"
import "react-datepicker/dist/react-datepicker.css";

import RightArrow from "../assets/img/right-arrow.png"
import section02Img01 from "../assets/img/SmartGuid2/section02Img01.png"
import section02Img02 from "../assets/img/SmartGuid2/section02Img02.png"
import section02Img03 from "../assets/img/SmartGuid2/section02Img03.png"
import section02Img04 from "../assets/img/SmartGuid2/section02Img04.png"
import section02Img05 from "../assets/img/SmartGuid2/section02Img05.png"
import section02Img06 from "../assets/img/SmartGuid2/section02Img06.png"
import section03Img from "../assets/img/SmartGuid2/section03Img.png"
import section04Img from "../assets/img/SmartGuid2/section04Img.png"


export default function SmartGuide() {

    return (
        <>
            <Head>
                <title>VEHDE - Smart Guide</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <MainLayout>
                <section id={styles.heroSection} className="heroSection" >
                    <div>
                        <div className='container'>
                            <div className='row row-cols-lg-2 gap-5'>
                                <div>
                                    <h1>Smart Guide</h1>
                                </div>
                                <div></div>
                            </div>
                        </div>
                    </div>
                </section>
                <section id={styles.section02}>
                    <div className="container">
                        <div className="wrapper">
                            <div className='text-center mb-5'>
                                <h2>How VEHDE works</h2>
                                <p>
                                    VEHDE works in six (6) major steps, carefully designed to enhance people’s productivity by improving their accessibility to mobility.
                                </p>
                            </div>
                            <div className="row row-cols-lg-3 row-cols-1 flex-lg-row flex-column align-items-center mt-5">
                                <div className="col d-flex flex-column align-items-lg-end align-items-center gap-5">
                                    <div className="d-flex align-items-center gap-3 flex-lg-row flex-row-reverse justify-content-end">
                                        <div className='text-start'>
                                            <h4>1. VEHDE approves listed cars</h4>
                                            <p>VEHDE reviews and approves cars listed by hosts.</p>
                                        </div>
                                        <div>
                                            <Image src={section02Img01} alt="" />
                                        </div>
                                    </div>
                                    <div className="d-flex align-items-center gap-3 justify-content-end flex-lg-row flex-row-reverse">
                                        <div className='text-start'>
                                            <h4>2. A renter reserves a car</h4>
                                            <p>Renter reviews available cars and requests a car of choice.</p>
                                        </div>
                                        <div>
                                            <Image src={section02Img02} alt="" />
                                        </div>
                                    </div>
                                    <div className="d-flex align-items-center gap-3 flex-lg-row flex-row-reverse justify-content-end">
                                        <div className='text-start'>
                                            <h4>3. VEHDE approves requested car</h4>
                                            <p>VEHDE approves renter’s request for car reservation. Host is notified about the renter’s reservation.</p>
                                        </div>
                                        <div>
                                            <Image src={section02Img03} alt="" />
                                        </div>
                                    </div>
                                </div>
                                <div className="col text-center">
                                    <h2 className='d-lg-block d-none' style={{ fontWeight: "bold" }}>VEHDE</h2>
                                </div>
                                <div className="col d-flex flex-lg-column flex-column-reverse align-items-lg-start align-items-center gap-5 mt-lg-0 mt-5">
                                    <div className="d-flex flex-row-reverse align-items-center gap-3 justify-content-lg-start justify-content-end">
                                        <div className='text-start'>
                                            <h4>6. Renter earns VEHDE points &nbsp; &nbsp; &nbsp; &nbsp;</h4>
                                            <p>For each completed car rental, renters and hosts earn VEHDE scores. VEHDE scores can be converted to rental or cash equivalent.</p>
                                        </div>
                                        <div>
                                            <Image src={section02Img04} alt="" />
                                        </div>
                                    </div>
                                    <div className="d-flex flex-row-reverse align-items-center gap-3 justify-content-end">
                                        <div className='text-start'>
                                            <h4>5. Renter returns the car</h4>
                                            <p>At the end of the rental period, host picks up the car at the drop-off location specified by the renter. Alternative arrangement for the car’s drop-off location is possible.</p>
                                        </div>
                                        <div>
                                            <Image src={section02Img05} alt="" />
                                        </div>
                                    </div>
                                    <div className="d-flex flex-row-reverse align-items-center gap-3 justify-content-lg-start justify-content-end">
                                        <div className='text-start'>
                                            <h4>4. Renter receives the reserved car</h4>
                                            <p>Renter receives delivery of the reserved car at the specified location, date, and time.</p>
                                        </div>
                                        <div>
                                            <Image src={section02Img06} alt="" />
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
                <section id={styles.section03} className="mb-5">
                    <div className="container">
                        <div className="wrapper">
                            <div className="row row-cols-lg-2 row-cols-1 align-items-center">
                                <div className="col p-5">
                                    <Image src={section03Img} alt="" className='img-fluid' />
                                </div>
                                <div className="col">
                                    <h2>What sets us apart</h2>
                                    <p>At VEHDE, we treat your payment for car’s rentals as an investment. That is why we are here to serve you better, in a way more productive manner.</p>
                                    <p>
                                        We developed our strategy based on our extensive experience in the transportation industry, and this is because we understand how sustainability continues to define the future of the transportation industry
                                    </p>
                                    <p>
                                        Our innovative strategy, with a great emphasis on sustainability, is carefully designed to optimize your return on investment.
                                    </p>
                                    <div className="d-flex align-items-center gap-3">
                                        <Link href="/UniqueBenefitswithVehde">Learn more about your unique benefits with VEHDE</Link> <Image src={RightArrow} alt="" />
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
                <section id={styles.section04} className="my-5">
                    <div className="container">
                        <div className="wrapper">
                            <div className="row row-cols-lg-2 row-cols-1 align-items-center">
                                <div className="col">
                                    <h2 style={{ fontWeight: 700 }}>Flexibility that supports you and your business</h2>
                                    <div className="row row-cols-md-2 row-cols-1 my-5">
                                        <div className="col d-flex align-items-center gap-2 mb-3">
                                            <input type="checkbox" name="manufacturers" id="rental-companies" defaultChecked />
                                            <label htmlFor="Manufacturers">Rental companies</label>
                                        </div>
                                        <div className="col d-flex align-items-center gap-2 mb-3">
                                            <input type="checkbox" name="corporateOrganizations" id="Corporate-organizations" />
                                            <label htmlFor="Corporate-organizations">Corporate organizations</label>
                                        </div>
                                        <div className="col d-flex align-items-center gap-2 mb-md-0 mb-3">
                                            <input type="checkbox" name="individuals" id="Individuals" />
                                            <label htmlFor="Individuals">Individuals</label>
                                        </div>
                                        <div className="col d-flex align-items-center gap-2">
                                            <input type="checkbox" name="manufacturers" id="Manufacturers" />
                                            <label htmlFor="Manufacturers">Manufacturers</label>
                                        </div>
                                    </div>
                                    <div className="d-flex align-items-center flex-lg-row flex-column gap-3">
                                        <Link href="#" className='my-btn'>&nbsp;&nbsp; Rent A Car &nbsp;&nbsp;</Link>
                                        <Link href="#" className='my-btn-outline'>Apply To Host</Link>
                                    </div>
                                </div>
                                <div className="col p-lg-5 p-3">
                                    <div className='text-center'>
                                        <label htmlFor="file" style={{ cursor: "pointer" }}>
                                            <Image src={section04Img} alt="" className='img-fluid' />
                                            <input type="file" name="file" id="file" hidden />
                                        </label>
                                        <button className='my-btn mx-auto mt-4 mb-2'>Submit Work</button>
                                        <p>
                                            General Information Request Tool
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
            </MainLayout>
        </>
    )
}