import Head from 'next/head'
import React from 'react'
import MainLayout from '../components/layout/MainLayout'
import styles from "../styles/WelcomeOnboard.module.css"

import Image from 'next/image'
import Link from 'next/link'
import Section02Img01 from "../assets/img/signin-up-with-vehde/section-02-img-01.png"
import Section02Img02 from "../assets/img/signin-up-with-vehde/section-02-img-02.png"

const WelcomeOnboard = () => {
    return (
        <>
            <Head>
                <title>VEHDE - Welcome Onboard</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <MainLayout>
                <section id={styles.heroSection} className="heroSection">
                    <div>
                        <div className="container">
                            <div className="wrapper">
                                <div className="row align-items-center">
                                    <div className="col-lg-5 mb-lg-0 mb-5">
                                        <h1>Get Started</h1>
                                        <h2>Welcome onboard, to VEHDE!</h2>
                                        <p>We bring you the greatest flexibility in the ever-growing carsharing sector of the transportation industry. Whether it is for your daily business activities, holiday leisure, or weekend trips, VEHDE is committed to improving people’s accessibility to a variety of cars in way more convenient arrangements.</p>
                                        <div className='d-flex'>
                                            <Link href="#" className='my-btn'>Browse available cars</Link>
                                        </div>
                                    </div>
                                    <div className="col-lg-7 text-center">
                                        {/* <Image src={HeroSectionImg} alt="Patent Vaccination Program Image" className='img-fluid' /> */}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
                <section id={styles.section02}>
                    <div className="container">
                        <div className="wrapper">
                            <div className="row row-cols-lg-2 row-cols-1 align-items-center">
                                <div className="col text-center">
                                    <Image src={Section02Img01} alt="Car in background Building" className='img-fluid' />
                                    <h3>Need a car to rent?</h3>
                                    <div className='d-flex justify-content-center'>
                                        <Link href="#" className='my-btn'>Apply to host</Link>
                                    </div>
                                </div>
                                <div className="col text-center mt-lg-0 mt-5">
                                    <Image src={Section02Img02} alt="Car in background Building" className='img-fluid' />
                                    <h3>Have a car to list as host?</h3>
                                    <div className='d-flex justify-content-center'>
                                        <Link href="#" className='my-btn'> &nbsp;&nbsp; Rent a car &nbsp;&nbsp; </Link>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
            </MainLayout>
        </>
    )
}

export default WelcomeOnboard